services:
  - type: web
    name: fad-helper
    env: python
    buildCommand: pip install -r requirements.txt; echo "Installing done"; python init_db_simple.py; echo "Database init done"
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
